<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C7K2DhTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C7K2DhT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.C7K2DhT.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.C7K2DhT": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'event' => 'App\\Entity\\Event',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.C7K2DhT'])) {
            return $container->privates['.service_locator.C7K2DhT'];
        }

        return $container->privates['.service_locator.C7K2DhT'] = $instance;
    }
}
