<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__IN4wWqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..IN4wWq' shared service.
     *
     * @return \App\Repository\AbonnementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\PricingController::index()": the $abonnementRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\AbonnementRepository".');
    }
}
