<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xzz46qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._xzz46q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._xzz46q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abonnementRepository' => ['privates', '.errored..IN4wWq', NULL, 'Cannot determine controller argument for "App\\Controller\\PricingController::index()": the $abonnementRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\AbonnementRepository".'],
        ], [
            'abonnementRepository' => '?',
        ]);
    }
}
