<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AO96L4mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AO96L4m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'athlete' => ['privates', '.errored..service_locator.AO96L4m.App\\Entity\\Athlete', NULL, 'Cannot autowire service ".service_locator.AO96L4m": it needs an instance of "App\\Entity\\Athlete" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'athlete' => 'App\\Entity\\Athlete',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.AO96L4m'])) {
            return $container->privates['.service_locator.AO96L4m'];
        }

        return $container->privates['.service_locator.AO96L4m'] = $instance;
    }
}
