<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jj0Jg6lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jj0Jg6l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'competition' => ['privates', '.errored..service_locator.Jj0Jg6l.App\\Entity\\Competition', NULL, 'Cannot autowire service ".service_locator.Jj0Jg6l": it needs an instance of "App\\Entity\\Competition" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'competition' => 'App\\Entity\\Competition',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.Jj0Jg6l'])) {
            return $container->privates['.service_locator.Jj0Jg6l'];
        }

        return $container->privates['.service_locator.Jj0Jg6l'] = $instance;
    }
}
