<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZV7NVrAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZV7NVrA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'licence' => ['privates', '.errored..service_locator.ZV7NVrA.App\\Entity\\Licence', NULL, 'Cannot autowire service ".service_locator.ZV7NVrA": it needs an instance of "App\\Entity\\Licence" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'licence' => 'App\\Entity\\Licence',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.ZV7NVrA'])) {
            return $container->privates['.service_locator.ZV7NVrA'];
        }

        return $container->privates['.service_locator.ZV7NVrA'] = $instance;
    }
}
