<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAthleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3K.nwkK.App\Entity\Athlete' shared service.
     *
     * @return \App\Entity\Athlete
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3K.nwkK": it needs an instance of "App\\Entity\\Athlete" but this type has been excluded in "config/services.yaml".');
    }
}
