<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSecurityControllerexportCsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LFUFYXp.App\Controller\Admin\AdminSecurityController::exportCsv()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LFUFYXp.App\\Controller\\Admin\\AdminSecurityController::exportCsv()'] = ($container->privates['.service_locator.LFUFYXp'] ?? $container->load('get_ServiceLocator_LFUFYXpService'))->withContext('App\\Controller\\Admin\\AdminSecurityController::exportCsv()', $container);
    }
}
