<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUsersControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YxhG_3W.App\Controller\Admin\AdminUsersController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'em' => '?',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminUsersController::new()', $container);

        if (isset($container->privates['.service_locator.YxhG_3W.App\\Controller\\Admin\\AdminUsersController::new()'])) {
            return $container->privates['.service_locator.YxhG_3W.App\\Controller\\Admin\\AdminUsersController::new()'];
        }

        return $container->privates['.service_locator.YxhG_3W.App\\Controller\\Admin\\AdminUsersController::new()'] = $instance;
    }
}
