<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssistantControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AssistantController' shared autowired service.
     *
     * @return \App\Controller\AssistantController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AssistantController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/EliosAiService.php';

        $container->services['App\\Controller\\AssistantController'] = $instance = new \App\Controller\AssistantController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Service\EliosAiService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GEMINI_API_KEY')));

        $instance->setContainer(($container->privates['.service_locator.EmKNLkt'] ?? $container->load('get_ServiceLocator_EmKNLktService'))->withContext('App\\Controller\\AssistantController', $container));

        return $instance;
    }
}
