<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kyWfXKr.App\Controller\Admin\AdminDashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kyWfXKr.App\\Controller\\Admin\\AdminDashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
            'logRepo' => ['privates', 'App\\Repository\\SecurityLogRepository', 'getSecurityLogRepositoryService', true],
            'subsRepo' => ['privates', 'App\\Repository\\NewsletterSubscriberRepository', 'getNewsletterSubscriberRepositoryService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'logRepo' => 'App\\Repository\\SecurityLogRepository',
            'subsRepo' => 'App\\Repository\\NewsletterSubscriberRepository',
        ]))->withContext('App\\Controller\\Admin\\AdminDashboardController::index()', $container);
    }
}
