<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUsersControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CQIMZqF.App\Controller\Admin\AdminUsersController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.CQIMZqF.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.CQIMZqF": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminUsersController::delete()', $container);

        if (isset($container->privates['.service_locator.CQIMZqF.App\\Controller\\Admin\\AdminUsersController::delete()'])) {
            return $container->privates['.service_locator.CQIMZqF.App\\Controller\\Admin\\AdminUsersController::delete()'];
        }

        return $container->privates['.service_locator.CQIMZqF.App\\Controller\\Admin\\AdminUsersController::delete()'] = $instance;
    }
}
