<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminClubInfoControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NNoa.Uk.App\Controller\Admin\AdminClubInfoController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.NNoa.Uk'] ?? $container->load('get_ServiceLocator_NNoa_UkService'));

        if (isset($container->privates['.service_locator.NNoa.Uk.App\\Controller\\Admin\\AdminClubInfoController::edit()'])) {
            return $container->privates['.service_locator.NNoa.Uk.App\\Controller\\Admin\\AdminClubInfoController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AdminClubInfoController::edit()', $container);

        if (isset($container->privates['.service_locator.NNoa.Uk.App\\Controller\\Admin\\AdminClubInfoController::edit()'])) {
            return $container->privates['.service_locator.NNoa.Uk.App\\Controller\\Admin\\AdminClubInfoController::edit()'];
        }

        return $container->privates['.service_locator.NNoa.Uk.App\\Controller\\Admin\\AdminClubInfoController::edit()'] = $instance;
    }
}
