<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSecurityControllersetupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aJLsdPj.App\Controller\Admin\AdminSecurityController::setup()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ga' => ['services', 'scheb_two_factor.security.google_authenticator', 'getSchebTwoFactor_Security_GoogleAuthenticatorService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ga' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminSecurityController::setup()', $container);

        if (isset($container->privates['.service_locator.aJLsdPj.App\\Controller\\Admin\\AdminSecurityController::setup()'])) {
            return $container->privates['.service_locator.aJLsdPj.App\\Controller\\Admin\\AdminSecurityController::setup()'];
        }

        return $container->privates['.service_locator.aJLsdPj.App\\Controller\\Admin\\AdminSecurityController::setup()'] = $instance;
    }
}
