<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetitionControllershowAthleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3K.nwkK.App\Controller\CompetitionController::showAthlete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3K.nwkK.App\\Controller\\CompetitionController::showAthlete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'athlete' => ['privates', '.errored..service_locator.3K.nwkK.App\\Entity\\Athlete', NULL, 'Cannot autowire service ".service_locator.3K.nwkK": it needs an instance of "App\\Entity\\Athlete" but this type has been excluded in "config/services.yaml".'],
        ], [
            'athlete' => 'App\\Entity\\Athlete',
        ]))->withContext('App\\Controller\\CompetitionController::showAthlete()', $container);
    }
}
