<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetitionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Jj0Jg6l.App\Entity\Competition' shared service.
     *
     * @return \App\Entity\Competition
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Jj0Jg6l": it needs an instance of "App\\Entity\\Competition" but this type has been excluded in "config/services.yaml".');
    }
}
