<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetitionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CompetitionController' shared autowired service.
     *
     * @return \App\Controller\CompetitionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CompetitionController.php';

        $container->services['App\\Controller\\CompetitionController'] = $instance = new \App\Controller\CompetitionController();

        $instance->setContainer(($container->privates['.service_locator.EmKNLkt'] ?? $container->load('get_ServiceLocator_EmKNLktService'))->withContext('App\\Controller\\CompetitionController', $container));

        return $instance;
    }
}
