<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\GoogleAuthenticator' shared autowired service.
     *
     * @return \App\Security\GoogleAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/src/Security/GoogleAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/ClientRegistry.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Security\\GoogleAuthenticator'])) {
            return $container->privates['App\\Security\\GoogleAuthenticator'];
        }
        $b = ($container->privates['App\\Service\\SystemLoggerService'] ?? $container->load('getSystemLoggerServiceService'));

        if (isset($container->privates['App\\Security\\GoogleAuthenticator'])) {
            return $container->privates['App\\Security\\GoogleAuthenticator'];
        }

        $instance = new \App\Security\GoogleAuthenticator(($container->services['knpu.oauth2.registry'] ??= new \KnpU\OAuth2ClientBundle\Client\ClientRegistry($container, ['google' => 'knpu.oauth2.client.google'])), $a, ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), $b);

        if (isset($container->privates['App\\Security\\GoogleAuthenticator'])) {
            return $container->privates['App\\Security\\GoogleAuthenticator'];
        }

        return $container->privates['App\\Security\\GoogleAuthenticator'] = $instance;
    }
}
