<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BhdlzBx.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'machineRepository' => ['privates', 'App\\Repository\\MachineRepository', 'getMachineRepositoryService', true],
            'forfaitRepository' => ['privates', 'App\\Repository\\ForfaitRepository', 'getForfaitRepositoryService', true],
            'newsletterService' => ['privates', 'App\\Service\\NewsletterService', 'getNewsletterServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'machineRepository' => 'App\\Repository\\MachineRepository',
            'forfaitRepository' => 'App\\Repository\\ForfaitRepository',
            'newsletterService' => 'App\\Service\\NewsletterService',
            'em' => '?',
        ]))->withContext('App\\Controller\\HomeController::index()', $container);

        if (isset($container->privates['.service_locator.BhdlzBx.App\\Controller\\HomeController::index()'])) {
            return $container->privates['.service_locator.BhdlzBx.App\\Controller\\HomeController::index()'];
        }

        return $container->privates['.service_locator.BhdlzBx.App\\Controller\\HomeController::index()'] = $instance;
    }
}
