<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\LogRepository' shared autowired service.
     *
     * @return \App\Repository\LogRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/LogRepository.php';

        return $container->privates['App\\Repository\\LogRepository'] = new \App\Repository\LogRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
