<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLicenceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LicenceType' shared autowired service.
     *
     * @return \App\Form\LicenceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LicenceType.php';

        return $container->privates['App\\Form\\LicenceType'] = new \App\Form\LicenceType();
    }
}
