<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\LoginSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\LoginSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/LoginSubscriber.php';

        $a = ($container->privates['App\\Service\\SystemLoggerService'] ?? $container->load('getSystemLoggerServiceService'));

        if (isset($container->privates['App\\EventSubscriber\\LoginSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LoginSubscriber'];
        }

        $instance = new \App\EventSubscriber\LoginSubscriber($a);

        if (isset($container->privates['App\\EventSubscriber\\LoginSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LoginSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\LoginSubscriber'] = $instance;
    }
}
