<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMachineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RVaU8SY.App\Entity\Machine' shared service.
     *
     * @return \App\Entity\Machine
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RVaU8SY": it needs an instance of "App\\Entity\\Machine" but this type has been excluded in "config/services.yaml".');
    }
}
