<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletterControllersubscribeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wlVk2T2.App\Controller\NewsletterController::subscribe()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'logger' => ['privates', 'App\\Service\\SystemLoggerService', 'getSystemLoggerServiceService', true],
            'turnstile' => ['privates', 'App\\Service\\TurnstileVerifierService', 'getTurnstileVerifierServiceService', true],
        ], [
            'em' => '?',
            'mailer' => '?',
            'logger' => 'App\\Service\\SystemLoggerService',
            'turnstile' => 'App\\Service\\TurnstileVerifierService',
        ]))->withContext('App\\Controller\\NewsletterController::subscribe()', $container);

        if (isset($container->privates['.service_locator.wlVk2T2.App\\Controller\\NewsletterController::subscribe()'])) {
            return $container->privates['.service_locator.wlVk2T2.App\\Controller\\NewsletterController::subscribe()'];
        }

        return $container->privates['.service_locator.wlVk2T2.App\\Controller\\NewsletterController::subscribe()'] = $instance;
    }
}
