<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletterServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\NewsletterService' shared autowired service.
     *
     * @return \App\Service\NewsletterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/NewsletterService.php';

        return $container->privates['App\\Service\\NewsletterService'] = new \App\Service\NewsletterService(($container->privates['App\\Repository\\NewsletterSubscriberRepository'] ?? $container->load('getNewsletterSubscriberRepositoryService')));
    }
}
