<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordControllersetPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mQz732S.App\Controller\PasswordController::setPassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'hasherFactory' => ['privates', 'security.password_hasher_factory', 'getSecurity_PasswordHasherFactoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'logger' => ['privates', 'App\\Service\\SystemLoggerService', 'getSystemLoggerServiceService', true],
        ], [
            'passwordHasher' => '?',
            'hasherFactory' => '?',
            'em' => '?',
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'logger' => 'App\\Service\\SystemLoggerService',
        ]))->withContext('App\\Controller\\PasswordController::setPassword()', $container);

        if (isset($container->privates['.service_locator.mQz732S.App\\Controller\\PasswordController::setPassword()'])) {
            return $container->privates['.service_locator.mQz732S.App\\Controller\\PasswordController::setPassword()'];
        }

        return $container->privates['.service_locator.mQz732S.App\\Controller\\PasswordController::setPassword()'] = $instance;
    }
}
