<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GW0h_ve.App\Controller\RegistrationController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'logger' => ['privates', 'App\\Service\\SystemLoggerService', 'getSystemLoggerServiceService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
        ], [
            'passwordHasher' => '?',
            'entityManager' => '?',
            'mailer' => '?',
            'logger' => 'App\\Service\\SystemLoggerService',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\RegistrationController::register()', $container);

        if (isset($container->privates['.service_locator.GW0h_ve.App\\Controller\\RegistrationController::register()'])) {
            return $container->privates['.service_locator.GW0h_ve.App\\Controller\\RegistrationController::register()'];
        }

        return $container->privates['.service_locator.GW0h_ve.App\\Controller\\RegistrationController::register()'] = $instance;
    }
}
