<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemLoggerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SystemLoggerService' shared autowired service.
     *
     * @return \App\Service\SystemLoggerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SystemLoggerService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\SystemLoggerService'])) {
            return $container->privates['App\\Service\\SystemLoggerService'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Service\\SystemLoggerService'])) {
            return $container->privates['App\\Service\\SystemLoggerService'];
        }

        $instance = new \App\Service\SystemLoggerService($a, $b, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\UserRepository'] ?? self::getUserRepositoryService($container)));

        if (isset($container->privates['App\\Service\\SystemLoggerService'])) {
            return $container->privates['App\\Service\\SystemLoggerService'];
        }

        return $container->privates['App\\Service\\SystemLoggerService'] = $instance;
    }
}
