<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityLogRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SecurityLogRepository' shared autowired service.
     *
     * @return \App\Repository\SecurityLogRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/SecurityLogRepository.php';

        return $container->privates['App\\Repository\\SecurityLogRepository'] = new \App\Repository\SecurityLogRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
