<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsAdminControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AtOyNC4.App\Controller\Admin\StatsAdminController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'subsRepo' => ['privates', 'App\\Repository\\NewsletterSubscriberRepository', 'getNewsletterSubscriberRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'articleRepo' => 'App\\Repository\\ArticleRepository',
            'subsRepo' => 'App\\Repository\\NewsletterSubscriberRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\StatsAdminController::index()', $container);

        if (isset($container->privates['.service_locator.AtOyNC4.App\\Controller\\Admin\\StatsAdminController::index()'])) {
            return $container->privates['.service_locator.AtOyNC4.App\\Controller\\Admin\\StatsAdminController::index()'];
        }

        return $container->privates['.service_locator.AtOyNC4.App\\Controller\\Admin\\StatsAdminController::index()'] = $instance;
    }
}
