<?php

namespace ContainerAAk41S2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZoneRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ZoneRepository' shared autowired service.
     *
     * @return \App\Repository\ZoneRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ZoneRepository.php';

        return $container->privates['App\\Repository\\ZoneRepository'] = new \App\Repository\ZoneRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
