<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NNoa_UkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NNoa.Uk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'info' => ['privates', '.errored..service_locator.NNoa.Uk.App\\Entity\\ClubInfo', NULL, 'Cannot autowire service ".service_locator.NNoa.Uk": it needs an instance of "App\\Entity\\ClubInfo" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'info' => 'App\\Entity\\ClubInfo',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.NNoa.Uk'])) {
            return $container->privates['.service_locator.NNoa.Uk'];
        }

        return $container->privates['.service_locator.NNoa.Uk'] = $instance;
    }
}
