<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4oiPVCYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4oiPVCY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'App\\Service\\SystemLoggerService', 'getSystemLoggerServiceService', true],
        ], [
            'em' => '?',
            'logger' => 'App\\Service\\SystemLoggerService',
        ]);

        if (isset($container->privates['.service_locator.4oiPVCY'])) {
            return $container->privates['.service_locator.4oiPVCY'];
        }

        return $container->privates['.service_locator.4oiPVCY'] = $instance;
    }
}
