<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V_3x1sgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V.3x1sg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'page' => ['privates', '.errored..service_locator.V.3x1sg.App\\Entity\\Page', NULL, 'Cannot autowire service ".service_locator.V.3x1sg": it needs an instance of "App\\Entity\\Page" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'page' => 'App\\Entity\\Page',
        ]);

        if (isset($container->privates['.service_locator.V.3x1sg'])) {
            return $container->privates['.service_locator.V.3x1sg'];
        }

        return $container->privates['.service_locator.V.3x1sg'] = $instance;
    }
}
