<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F0f6OVtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f0f6OVt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f0f6OVt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'forfaitRepository' => ['privates', 'App\\Repository\\ForfaitRepository', 'getForfaitRepositoryService', true],
        ], [
            'forfaitRepository' => 'App\\Repository\\ForfaitRepository',
        ]);
    }
}
