<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BQ1SEPDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bQ1SEPD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'forfait' => ['privates', '.errored..service_locator.bQ1SEPD.App\\Entity\\Forfait', NULL, 'Cannot autowire service ".service_locator.bQ1SEPD": it needs an instance of "App\\Entity\\Forfait" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'forfait' => 'App\\Entity\\Forfait',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.bQ1SEPD'])) {
            return $container->privates['.service_locator.bQ1SEPD'];
        }

        return $container->privates['.service_locator.bQ1SEPD'] = $instance;
    }
}
