<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminMachineControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d.K5QNB.App\Controller\Admin\AdminMachineController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d.K5QNB.App\\Controller\\Admin\\AdminMachineController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\MachineRepository', 'getMachineRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\MachineRepository',
        ]))->withContext('App\\Controller\\Admin\\AdminMachineController::index()', $container);
    }
}
