<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleAdminControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e51BVih.App\Controller\Admin\ArticleAdminController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.e51BVih'] ?? $container->load('get_ServiceLocator_E51BVihService'));

        if (isset($container->privates['.service_locator.e51BVih.App\\Controller\\Admin\\ArticleAdminController::delete()'])) {
            return $container->privates['.service_locator.e51BVih.App\\Controller\\Admin\\ArticleAdminController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\ArticleAdminController::delete()', $container);

        if (isset($container->privates['.service_locator.e51BVih.App\\Controller\\Admin\\ArticleAdminController::delete()'])) {
            return $container->privates['.service_locator.e51BVih.App\\Controller\\Admin\\ArticleAdminController::delete()'];
        }

        return $container->privates['.service_locator.e51BVih.App\\Controller\\Admin\\ArticleAdminController::delete()'] = $instance;
    }
}
