<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSecurityControllerbanIpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.leGR8db.App\Controller\Admin\AdminSecurityController::banIp()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\SecurityLogRepository', 'getSecurityLogRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\SecurityLogRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminSecurityController::banIp()', $container);

        if (isset($container->privates['.service_locator.leGR8db.App\\Controller\\Admin\\AdminSecurityController::banIp()'])) {
            return $container->privates['.service_locator.leGR8db.App\\Controller\\Admin\\AdminSecurityController::banIp()'];
        }

        return $container->privates['.service_locator.leGR8db.App\\Controller\\Admin\\AdminSecurityController::banIp()'] = $instance;
    }
}
