<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminNewsletterControllercomposeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LLFq5vu.App\Controller\Admin\AdminNewsletterController::compose()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'mailer' => '?',
            'em' => '?',
            'urlGenerator' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminNewsletterController::compose()', $container);

        if (isset($container->privates['.service_locator.LLFq5vu.App\\Controller\\Admin\\AdminNewsletterController::compose()'])) {
            return $container->privates['.service_locator.LLFq5vu.App\\Controller\\Admin\\AdminNewsletterController::compose()'];
        }

        return $container->privates['.service_locator.LLFq5vu.App\\Controller\\Admin\\AdminNewsletterController::compose()'] = $instance;
    }
}
