<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminLicenceControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZV7NVrA.App\Controller\Admin\AdminLicenceController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ZV7NVrA'] ?? $container->load('get_ServiceLocator_ZV7NVrAService'));

        if (isset($container->privates['.service_locator.ZV7NVrA.App\\Controller\\Admin\\AdminLicenceController::delete()'])) {
            return $container->privates['.service_locator.ZV7NVrA.App\\Controller\\Admin\\AdminLicenceController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AdminLicenceController::delete()', $container);

        if (isset($container->privates['.service_locator.ZV7NVrA.App\\Controller\\Admin\\AdminLicenceController::delete()'])) {
            return $container->privates['.service_locator.ZV7NVrA.App\\Controller\\Admin\\AdminLicenceController::delete()'];
        }

        return $container->privates['.service_locator.ZV7NVrA.App\\Controller\\Admin\\AdminLicenceController::delete()'] = $instance;
    }
}
