<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssistantControllerrequestLicenceCodeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HKv6Vyy.App\Controller\AssistantController::requestLicenceCode()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'mailer' => '?',
        ]))->withContext('App\\Controller\\AssistantController::requestLicenceCode()', $container);

        if (isset($container->privates['.service_locator.HKv6Vyy.App\\Controller\\AssistantController::requestLicenceCode()'])) {
            return $container->privates['.service_locator.HKv6Vyy.App\\Controller\\AssistantController::requestLicenceCode()'];
        }

        return $container->privates['.service_locator.HKv6Vyy.App\\Controller\\AssistantController::requestLicenceCode()'] = $instance;
    }
}
