<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSecurityControllerunlockUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OA38qqg.App\Controller\Admin\AdminSecurityController::unlockUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminSecurityController::unlockUser()', $container);

        if (isset($container->privates['.service_locator.OA38qqg.App\\Controller\\Admin\\AdminSecurityController::unlockUser()'])) {
            return $container->privates['.service_locator.OA38qqg.App\\Controller\\Admin\\AdminSecurityController::unlockUser()'];
        }

        return $container->privates['.service_locator.OA38qqg.App\\Controller\\Admin\\AdminSecurityController::unlockUser()'] = $instance;
    }
}
