<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminAthleteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AO96L4m.App\Controller\Admin\AdminAthleteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.AO96L4m'] ?? $container->load('get_ServiceLocator_AO96L4mService'));

        if (isset($container->privates['.service_locator.AO96L4m.App\\Controller\\Admin\\AdminAthleteController::edit()'])) {
            return $container->privates['.service_locator.AO96L4m.App\\Controller\\Admin\\AdminAthleteController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AdminAthleteController::edit()', $container);

        if (isset($container->privates['.service_locator.AO96L4m.App\\Controller\\Admin\\AdminAthleteController::edit()'])) {
            return $container->privates['.service_locator.AO96L4m.App\\Controller\\Admin\\AdminAthleteController::edit()'];
        }

        return $container->privates['.service_locator.AO96L4m.App\\Controller\\Admin\\AdminAthleteController::edit()'] = $instance;
    }
}
