<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminForfaitControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bQ1SEPD.App\Controller\Admin\AdminForfaitController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.bQ1SEPD'] ?? $container->load('get_ServiceLocator_BQ1SEPDService'));

        if (isset($container->privates['.service_locator.bQ1SEPD.App\\Controller\\Admin\\AdminForfaitController::delete()'])) {
            return $container->privates['.service_locator.bQ1SEPD.App\\Controller\\Admin\\AdminForfaitController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AdminForfaitController::delete()', $container);

        if (isset($container->privates['.service_locator.bQ1SEPD.App\\Controller\\Admin\\AdminForfaitController::delete()'])) {
            return $container->privates['.service_locator.bQ1SEPD.App\\Controller\\Admin\\AdminForfaitController::delete()'];
        }

        return $container->privates['.service_locator.bQ1SEPD.App\\Controller\\Admin\\AdminForfaitController::delete()'] = $instance;
    }
}
