<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminManagementControllernewAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AmBpoVg.App\Controller\Admin\AdminManagementController::newAdmin()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'ga' => ['services', 'scheb_two_factor.security.google_authenticator', 'getSchebTwoFactor_Security_GoogleAuthenticatorService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'em' => '?',
            'hasher' => '?',
            'ga' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminManagementController::newAdmin()', $container);

        if (isset($container->privates['.service_locator.AmBpoVg.App\\Controller\\Admin\\AdminManagementController::newAdmin()'])) {
            return $container->privates['.service_locator.AmBpoVg.App\\Controller\\Admin\\AdminManagementController::newAdmin()'];
        }

        return $container->privates['.service_locator.AmBpoVg.App\\Controller\\Admin\\AdminManagementController::newAdmin()'] = $instance;
    }
}
