<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSecurityControllerpurgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LhS3l84.App\Controller\Admin\AdminSecurityController::purge()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\SecurityLogRepository', 'getSecurityLogRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\SecurityLogRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminSecurityController::purge()', $container);

        if (isset($container->privates['.service_locator.LhS3l84.App\\Controller\\Admin\\AdminSecurityController::purge()'])) {
            return $container->privates['.service_locator.LhS3l84.App\\Controller\\Admin\\AdminSecurityController::purge()'];
        }

        return $container->privates['.service_locator.LhS3l84.App\\Controller\\Admin\\AdminSecurityController::purge()'] = $instance;
    }
}
