<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEventControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ViUb538.App\Controller\Admin\AdminEventController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ViUb538.App\\Controller\\Admin\\AdminEventController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventRepo' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'eventRepo' => 'App\\Repository\\EventRepository',
        ]))->withContext('App\\Controller\\Admin\\AdminEventController::index()', $container);
    }
}
