<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEventControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C7K2DhT.App\Controller\Admin\AdminEventController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.C7K2DhT'] ?? $container->load('get_ServiceLocator_C7K2DhTService'));

        if (isset($container->privates['.service_locator.C7K2DhT.App\\Controller\\Admin\\AdminEventController::edit()'])) {
            return $container->privates['.service_locator.C7K2DhT.App\\Controller\\Admin\\AdminEventController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AdminEventController::edit()', $container);

        if (isset($container->privates['.service_locator.C7K2DhT.App\\Controller\\Admin\\AdminEventController::edit()'])) {
            return $container->privates['.service_locator.C7K2DhT.App\\Controller\\Admin\\AdminEventController::edit()'];
        }

        return $container->privates['.service_locator.C7K2DhT.App\\Controller\\Admin\\AdminEventController::edit()'] = $instance;
    }
}
