<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminForfaitControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f0f6OVt.App\Controller\Admin\AdminForfaitController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f0f6OVt.App\\Controller\\Admin\\AdminForfaitController::index()'] = ($container->privates['.service_locator.f0f6OVt'] ?? $container->load('get_ServiceLocator_F0f6OVtService'))->withContext('App\\Controller\\Admin\\AdminForfaitController::index()', $container);
    }
}
