<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSettingsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\AdminSettingsController' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminSettingsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/AdminSettingsController.php';

        $container->services['App\\Controller\\Admin\\AdminSettingsController'] = $instance = new \App\Controller\Admin\AdminSettingsController();

        $instance->setContainer(($container->privates['.service_locator.EmKNLkt'] ?? $container->load('get_ServiceLocator_EmKNLktService'))->withContext('App\\Controller\\Admin\\AdminSettingsController', $container));

        return $instance;
    }
}
