<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProduitControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R2JxSTf.App\Controller\Admin\AdminProduitController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.R2JxSTf'] ?? $container->load('get_ServiceLocator_R2JxSTfService'));

        if (isset($container->privates['.service_locator.R2JxSTf.App\\Controller\\Admin\\AdminProduitController::delete()'])) {
            return $container->privates['.service_locator.R2JxSTf.App\\Controller\\Admin\\AdminProduitController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AdminProduitController::delete()', $container);

        if (isset($container->privates['.service_locator.R2JxSTf.App\\Controller\\Admin\\AdminProduitController::delete()'])) {
            return $container->privates['.service_locator.R2JxSTf.App\\Controller\\Admin\\AdminProduitController::delete()'];
        }

        return $container->privates['.service_locator.R2JxSTf.App\\Controller\\Admin\\AdminProduitController::delete()'] = $instance;
    }
}
