<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetitionAdminControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jj0Jg6l.App\Controller\Admin\CompetitionAdminController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Jj0Jg6l'] ?? $container->load('get_ServiceLocator_Jj0Jg6lService'));

        if (isset($container->privates['.service_locator.Jj0Jg6l.App\\Controller\\Admin\\CompetitionAdminController::delete()'])) {
            return $container->privates['.service_locator.Jj0Jg6l.App\\Controller\\Admin\\CompetitionAdminController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\CompetitionAdminController::delete()', $container);

        if (isset($container->privates['.service_locator.Jj0Jg6l.App\\Controller\\Admin\\CompetitionAdminController::delete()'])) {
            return $container->privates['.service_locator.Jj0Jg6l.App\\Controller\\Admin\\CompetitionAdminController::delete()'];
        }

        return $container->privates['.service_locator.Jj0Jg6l.App\\Controller\\Admin\\CompetitionAdminController::delete()'] = $instance;
    }
}
