<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactAdminControllerreplyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mCBcQKi.App\Controller\Admin\ContactAdminController::reply()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'message' => ['privates', '.errored..service_locator.mCBcQKi.App\\Entity\\ContactMessage', NULL, 'Cannot autowire service ".service_locator.mCBcQKi": it needs an instance of "App\\Entity\\ContactMessage" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'message' => 'App\\Entity\\ContactMessage',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\ContactAdminController::reply()', $container);

        if (isset($container->privates['.service_locator.mCBcQKi.App\\Controller\\Admin\\ContactAdminController::reply()'])) {
            return $container->privates['.service_locator.mCBcQKi.App\\Controller\\Admin\\ContactAdminController::reply()'];
        }

        return $container->privates['.service_locator.mCBcQKi.App\\Controller\\Admin\\ContactAdminController::reply()'] = $instance;
    }
}
