<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactMessageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ContactMessageType' shared autowired service.
     *
     * @return \App\Form\ContactMessageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ContactMessageType.php';

        return $container->privates['App\\Form\\ContactMessageType'] = new \App\Form\ContactMessageType();
    }
}
