<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardAdherentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DashboardAdherentController' shared autowired service.
     *
     * @return \App\Controller\DashboardAdherentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DashboardAdherentController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/EventMailer.php';

        $container->services['App\\Controller\\DashboardAdherentController'] = $instance = new \App\Controller\DashboardAdherentController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.csrf.same_origin_token_manager'] ?? self::getSecurity_Csrf_SameOriginTokenManagerService($container)), new \App\Service\EventMailer(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['twig'] ?? $container->load('getTwigService'))));

        $instance->setContainer(($container->privates['.service_locator.EmKNLkt'] ?? $container->load('get_ServiceLocator_EmKNLktService'))->withContext('App\\Controller\\DashboardAdherentController', $container));

        return $instance;
    }
}
