<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeExtension_CsrfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.type_extension.csrf' shared service.
     *
     * @return \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Csrf/Type/FormTypeCsrfExtension.php';

        return $container->privates['form.type_extension.csrf'] = new \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension(($container->privates['security.csrf.same_origin_token_manager'] ?? self::getSecurity_Csrf_SameOriginTokenManagerService($container)), true, '_token', NULL, 'validators', ($container->privates['form.server_params'] ?? $container->load('getForm_ServerParamsService')), $container->parameters['form.type_extension.csrf.field_attr'], ['App\\Form\\ArticleType' => 'submit', 'App\\Form\\AthleteType' => 'submit', 'App\\Form\\ClubInfoType' => 'submit', 'App\\Form\\CompetitionType' => 'submit', 'App\\Form\\ContactMessageType' => 'submit', 'App\\Form\\EventType' => 'submit', 'App\\Form\\ForfaitType' => 'submit', 'App\\Form\\LicenceType' => 'submit', 'App\\Form\\MachineType' => 'submit', 'App\\Form\\PageType' => 'submit', 'App\\Form\\ProduitType' => 'submit', 'App\\Form\\ProfileImageType' => 'submit', 'App\\Form\\RegistrationFormType' => 'submit', 'App\\Form\\ResetPasswordFormType' => 'submit', 'App\\Form\\ResetPasswordRequestFormType' => 'submit', 'App\\Form\\ResultType' => 'submit', 'App\\Form\\SetPasswordType' => 'submit', 'App\\Form\\SubscriberType' => 'submit', 'App\\Form\\UserType' => 'submit']);
    }
}
