<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForfaitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bQ1SEPD.App\Entity\Forfait' shared service.
     *
     * @return \App\Entity\Forfait
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bQ1SEPD": it needs an instance of "App\\Entity\\Forfait" but this type has been excluded in "config/services.yaml".');
    }
}
