<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginFormAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Authenticator\LoginFormAuthenticator' shared autowired service.
     *
     * @return \App\Authenticator\LoginFormAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractLoginFormAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/src/Authenticator/LoginFormAuthenticator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Authenticator\\LoginFormAuthenticator'])) {
            return $container->privates['App\\Authenticator\\LoginFormAuthenticator'];
        }
        $b = ($container->privates['App\\Service\\SystemLoggerService'] ?? $container->load('getSystemLoggerServiceService'));

        if (isset($container->privates['App\\Authenticator\\LoginFormAuthenticator'])) {
            return $container->privates['App\\Authenticator\\LoginFormAuthenticator'];
        }

        $instance = new \App\Authenticator\LoginFormAuthenticator(($container->services['router'] ?? self::getRouterService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Repository\\UserRepository'] ?? self::getUserRepositoryService($container)), $a, $b);

        if (isset($container->privates['App\\Authenticator\\LoginFormAuthenticator'])) {
            return $container->privates['App\\Authenticator\\LoginFormAuthenticator'];
        }

        return $container->privates['App\\Authenticator\\LoginFormAuthenticator'] = $instance;
    }
}
