<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogsAdminControllerInvokeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LyWZGDi.App\Controller\Admin\LogsAdminController::__invoke()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LyWZGDi.App\\Controller\\Admin\\LogsAdminController::__invoke()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'logRepo' => ['privates', 'App\\Repository\\LogRepository', 'getLogRepositoryService', true],
        ], [
            'logRepo' => 'App\\Repository\\LogRepository',
        ]))->withContext('App\\Controller\\Admin\\LogsAdminController::__invoke()', $container);
    }
}
