<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLicenceControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wyKZNgE.App\Controller\LicenceController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.wyKZNgE'] ?? $container->load('get_ServiceLocator_WyKZNgEService'));

        if (isset($container->privates['.service_locator.wyKZNgE.App\\Controller\\LicenceController::add()'])) {
            return $container->privates['.service_locator.wyKZNgE.App\\Controller\\LicenceController::add()'];
        }

        $instance = $a->withContext('App\\Controller\\LicenceController::add()', $container);

        if (isset($container->privates['.service_locator.wyKZNgE.App\\Controller\\LicenceController::add()'])) {
            return $container->privates['.service_locator.wyKZNgE.App\\Controller\\LicenceController::add()'];
        }

        return $container->privates['.service_locator.wyKZNgE.App\\Controller\\LicenceController::add()'] = $instance;
    }
}
