<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletterCampaignRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\NewsletterCampaignRepository' shared autowired service.
     *
     * @return \App\Repository\NewsletterCampaignRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/NewsletterCampaignRepository.php';

        return $container->privates['App\\Repository\\NewsletterCampaignRepository'] = new \App\Repository\NewsletterCampaignRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
