<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletterControllerunsubscribeByTokenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4oiPVCY.App\Controller\NewsletterController::unsubscribeByToken()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.4oiPVCY'] ?? $container->load('get_ServiceLocator_4oiPVCYService'));

        if (isset($container->privates['.service_locator.4oiPVCY.App\\Controller\\NewsletterController::unsubscribeByToken()'])) {
            return $container->privates['.service_locator.4oiPVCY.App\\Controller\\NewsletterController::unsubscribeByToken()'];
        }

        $instance = $a->withContext('App\\Controller\\NewsletterController::unsubscribeByToken()', $container);

        if (isset($container->privates['.service_locator.4oiPVCY.App\\Controller\\NewsletterController::unsubscribeByToken()'])) {
            return $container->privates['.service_locator.4oiPVCY.App\\Controller\\NewsletterController::unsubscribeByToken()'];
        }

        return $container->privates['.service_locator.4oiPVCY.App\\Controller\\NewsletterController::unsubscribeByToken()'] = $instance;
    }
}
