<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tQZj7eA.App\Controller\PageController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tQZj7eA.App\\Controller\\PageController::show()'] = ($container->privates['.service_locator.tQZj7eA'] ?? $container->load('get_ServiceLocator_TQZj7eAService'))->withContext('App\\Controller\\PageController::show()', $container);
    }
}
