<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageAdminControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V.3x1sg.App\Controller\Admin\PageAdminController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.V.3x1sg'] ?? $container->load('get_ServiceLocator_V_3x1sgService'));

        if (isset($container->privates['.service_locator.V.3x1sg.App\\Controller\\Admin\\PageAdminController::delete()'])) {
            return $container->privates['.service_locator.V.3x1sg.App\\Controller\\Admin\\PageAdminController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\PageAdminController::delete()', $container);

        if (isset($container->privates['.service_locator.V.3x1sg.App\\Controller\\Admin\\PageAdminController::delete()'])) {
            return $container->privates['.service_locator.V.3x1sg.App\\Controller\\Admin\\PageAdminController::delete()'];
        }

        return $container->privates['.service_locator.V.3x1sg.App\\Controller\\Admin\\PageAdminController::delete()'] = $instance;
    }
}
