<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordControllerrequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..TmV2E_.App\Controller\ResetPasswordController::request()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'logger' => ['privates', 'App\\Service\\SystemLoggerService', 'getSystemLoggerServiceService', true],
            'twig' => ['privates', 'twig', 'getTwigService', true],
        ], [
            'em' => '?',
            'mailer' => '?',
            'logger' => 'App\\Service\\SystemLoggerService',
            'twig' => '?',
        ]))->withContext('App\\Controller\\ResetPasswordController::request()', $container);

        if (isset($container->privates['.service_locator..TmV2E_.App\\Controller\\ResetPasswordController::request()'])) {
            return $container->privates['.service_locator..TmV2E_.App\\Controller\\ResetPasswordController::request()'];
        }

        return $container->privates['.service_locator..TmV2E_.App\\Controller\\ResetPasswordController::request()'] = $instance;
    }
}
