<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordControllerresetPasswordFinalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H11bJ_m.App\Controller\ResetPasswordController::resetPasswordFinal()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'App\\Service\\SystemLoggerService', 'getSystemLoggerServiceService', true],
            'passwordHasherFactory' => ['privates', 'security.password_hasher_factory', 'getSecurity_PasswordHasherFactoryService', true],
        ], [
            'em' => '?',
            'logger' => 'App\\Service\\SystemLoggerService',
            'passwordHasherFactory' => '?',
        ]))->withContext('App\\Controller\\ResetPasswordController::resetPasswordFinal()', $container);

        if (isset($container->privates['.service_locator.H11bJ_m.App\\Controller\\ResetPasswordController::resetPasswordFinal()'])) {
            return $container->privates['.service_locator.H11bJ_m.App\\Controller\\ResetPasswordController::resetPasswordFinal()'];
        }

        return $container->privates['.service_locator.H11bJ_m.App\\Controller\\ResetPasswordController::resetPasswordFinal()'] = $instance;
    }
}
