<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_Security_Totp_Validator_UserGoogleTotpCodeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'scheb_two_factor.security.totp.validator.user_google_totp_code' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\TwoFactor\Validator\Constraints\UserGoogleTotpCodeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-google-authenticator/Security/TwoFactor/Validator/Constraints/UserGoogleTotpCodeValidator.php';

        return $container->privates['scheb_two_factor.security.totp.validator.user_google_totp_code'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Validator\Constraints\UserGoogleTotpCodeValidator(($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['scheb_two_factor.security.google_authenticator'] ?? $container->load('getSchebTwoFactor_Security_GoogleAuthenticatorService')));
    }
}
