<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityLogSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\SecurityLogSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\SecurityLogSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/SecurityLogSubscriber.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventSubscriber\\SecurityLogSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\SecurityLogSubscriber'];
        }

        $instance = new \App\EventSubscriber\SecurityLogSubscriber($a);

        if (isset($container->privates['App\\EventSubscriber\\SecurityLogSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\SecurityLogSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\SecurityLogSubscriber'] = $instance;
    }
}
