<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTurnstileVerifierServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TurnstileVerifierService' shared autowired service.
     *
     * @return \App\Service\TurnstileVerifierService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/TurnstileVerifierService.php';

        return $container->privates['App\\Service\\TurnstileVerifierService'] = new \App\Service\TurnstileVerifierService($container->getEnv('TURNSTILE_SECRET_KEY'));
    }
}
