<?php

namespace ContainerLdVQ3CC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyCodeControllerverifyCodeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pehpjie.App\Controller\VerifyCodeController::verifyCode()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'App\\Service\\SystemLoggerService', 'getSystemLoggerServiceService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'entityManager' => '?',
            'logger' => 'App\\Service\\SystemLoggerService',
        ]))->withContext('App\\Controller\\VerifyCodeController::verifyCode()', $container);

        if (isset($container->privates['.service_locator.Pehpjie.App\\Controller\\VerifyCodeController::verifyCode()'])) {
            return $container->privates['.service_locator.Pehpjie.App\\Controller\\VerifyCodeController::verifyCode()'];
        }

        return $container->privates['.service_locator.Pehpjie.App\\Controller\\VerifyCodeController::verifyCode()'] = $instance;
    }
}
