<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acceptedTerms' => [parent::class, 'acceptedTerms', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'events' => [parent::class, 'events', null, 16],
        "\0".parent::class."\0".'failedAttempts' => [parent::class, 'failedAttempts', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'googleAuthenticatorSecret' => [parent::class, 'googleAuthenticatorSecret', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isTotpConfirmed' => [parent::class, 'isTotpConfirmed', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        "\0".parent::class."\0".'lastLoginIp' => [parent::class, 'lastLoginIp', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'lastResetRequestAt' => [parent::class, 'lastResetRequestAt', null, 16],
        "\0".parent::class."\0".'licenceEndDate' => [parent::class, 'licenceEndDate', null, 16],
        "\0".parent::class."\0".'licenceNumber' => [parent::class, 'licenceNumber', null, 16],
        "\0".parent::class."\0".'licenceStatus' => [parent::class, 'licenceStatus', null, 16],
        "\0".parent::class."\0".'licenceType' => [parent::class, 'licenceType', null, 16],
        "\0".parent::class."\0".'licences' => [parent::class, 'licences', null, 16],
        "\0".parent::class."\0".'lockedUntil' => [parent::class, 'lockedUntil', null, 16],
        "\0".parent::class."\0".'needsPassword' => [parent::class, 'needsPassword', null, 16],
        "\0".parent::class."\0".'newsletterSubscription' => [parent::class, 'newsletterSubscription', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'passwordHistories' => [parent::class, 'passwordHistories', null, 16],
        "\0".parent::class."\0".'payments' => [parent::class, 'payments', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'phoneVerified' => [parent::class, 'phoneVerified', null, 16],
        "\0".parent::class."\0".'profileImage' => [parent::class, 'profileImage', null, 16],
        "\0".parent::class."\0".'profileImageMime' => [parent::class, 'profileImageMime', null, 16],
        "\0".parent::class."\0".'profileImageUpdatedAt' => [parent::class, 'profileImageUpdatedAt', null, 16],
        "\0".parent::class."\0".'resetToken' => [parent::class, 'resetToken', null, 16],
        "\0".parent::class."\0".'resetTokenExpiresAt' => [parent::class, 'resetTokenExpiresAt', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'securityLogs' => [parent::class, 'securityLogs', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'userEvents' => [parent::class, 'userEvents', null, 16],
        "\0".parent::class."\0".'verificationCode' => [parent::class, 'verificationCode', null, 16],
        "\0".parent::class."\0".'verificationCodeExpiresAt' => [parent::class, 'verificationCodeExpiresAt', null, 16],
        'acceptedTerms' => [parent::class, 'acceptedTerms', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'events' => [parent::class, 'events', null, 16],
        'failedAttempts' => [parent::class, 'failedAttempts', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'googleAuthenticatorSecret' => [parent::class, 'googleAuthenticatorSecret', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isTotpConfirmed' => [parent::class, 'isTotpConfirmed', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        'lastLoginIp' => [parent::class, 'lastLoginIp', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'lastResetRequestAt' => [parent::class, 'lastResetRequestAt', null, 16],
        'licenceEndDate' => [parent::class, 'licenceEndDate', null, 16],
        'licenceNumber' => [parent::class, 'licenceNumber', null, 16],
        'licenceStatus' => [parent::class, 'licenceStatus', null, 16],
        'licenceType' => [parent::class, 'licenceType', null, 16],
        'licences' => [parent::class, 'licences', null, 16],
        'lockedUntil' => [parent::class, 'lockedUntil', null, 16],
        'needsPassword' => [parent::class, 'needsPassword', null, 16],
        'newsletterSubscription' => [parent::class, 'newsletterSubscription', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'passwordHistories' => [parent::class, 'passwordHistories', null, 16],
        'payments' => [parent::class, 'payments', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'phoneVerified' => [parent::class, 'phoneVerified', null, 16],
        'profileImage' => [parent::class, 'profileImage', null, 16],
        'profileImageMime' => [parent::class, 'profileImageMime', null, 16],
        'profileImageUpdatedAt' => [parent::class, 'profileImageUpdatedAt', null, 16],
        'resetToken' => [parent::class, 'resetToken', null, 16],
        'resetTokenExpiresAt' => [parent::class, 'resetTokenExpiresAt', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'securityLogs' => [parent::class, 'securityLogs', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'userEvents' => [parent::class, 'userEvents', null, 16],
        'verificationCode' => [parent::class, 'verificationCode', null, 16],
        'verificationCodeExpiresAt' => [parent::class, 'verificationCodeExpiresAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
