imports:
    - { resource: "faq.yaml" }

parameters:
    upload_dir: "%kernel.project_dir%/public/uploads"
    competitions_upload_dir: "%kernel.project_dir%/public/uploads/competitions"
    images_directory: "%kernel.project_dir%/public/uploads"
    machines_directory: "%kernel.project_dir%/public/uploads/machines"
    uploads_directory: "%kernel.project_dir%/public/uploads"
    env(TURNSTILE_SITE_KEY): ""

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: "%kernel.project_dir%"
            $geminiApiKey: "%env(GEMINI_API_KEY)%"
            $faqs: "%faq%"

            $registerLimiter: "@limiter.register"
            $loginLimiter: "@limiter.login"
            $verifyCodeLimiter: "@limiter.verify_code"
            $resendCodeLimiter: "@limiter.resend_code"
            $resetRequestLimiter: "@limiter.reset_request"
            $resetFinalLimiter: "@limiter.reset_final"
            $setPasswordLimiter: "@limiter.set_password"
            $googleOauthCheckLimiter: "@limiter.google_oauth_check"

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Migrations/"
            - "../src/Tests/"
            - "../src/Kernel.php"

    App\EventListener\LoginAttemptListener:
        tags:
            - {
                  name: kernel.event_listener,
                  event: Symfony\Component\Security\Http\Event\LoginFailureEvent,
                  method: onLoginFailure,
              }
            - {
                  name: kernel.event_listener,
                  event: Symfony\Component\Security\Http\Event\InteractiveLoginEvent,
                  method: onInteractiveLogin,
              }
            - {
                  name: kernel.event_listener,
                  event: kernel.request,
                  method: checkSessionContext,
              }

    App\Service\TurnstileVerifierService:
        arguments:
            $secretKey: "%env(TURNSTILE_SECRET_KEY)%"

    # ============================================================
    # SESSION EXPIRÉE
    # ============================================================
    App\EventListener\SessionExpiredListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # ============================================================
    # GEO BLOCKER + VPN BLOCKER
    # ============================================================
    App\Security\GeoBlocker:
        arguments:
            $allowedCountry: "%env(string:GEO_ALLOWED_COUNTRY)%"
            $blockVpn: "%env(bool:GEO_BLOCK_VPN)%"
