<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLdVQ3CC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLdVQ3CC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLdVQ3CC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLdVQ3CC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLdVQ3CC\App_KernelDevDebugContainer([
    'container.build_hash' => 'LdVQ3CC',
    'container.build_id' => '0f9642a0',
    'container.build_time' => 1770035254,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLdVQ3CC');
